version: '3.8'
services:
    action:
        container_name: sb-action
        working_dir: /app
        user: $DOCKER_USER
        tty: true
        build:
            context: .
            dockerfile: ./docker/actions/Dockerfile
        volumes:
            - .:/app
            - ./docker/actions/database.sqlite:/app/database.sqlite