name: Docker Image Publish

on:
  pull_request:
  push: { branches: master }

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Start docker
        run: make actions
      -
        name: Run backend tests
        run: docker compose exec php composer test
      -
        name: Run frontend tests
        run: docker compose exec node npm run test